sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5t7ofd8t22jf5Fn4fC4V
    access-key-secret: YOyXoKmwe2PyypukQdvaoHEglK5RK7
    bucket-name: yfh-waimai
    endpoint: oss-cn-beijing.aliyuncs.com
